plugins { id 'com.android.application' }
android {
 namespace 'com.topsai.dishwasher'
 useLibrary 'android.test.runner'
 useLibrary 'android.test.base'
 useLibrary 'android.test.mock'
 compileSdk 36
 buildToolsVersion '36.0.0'
 defaultConfig { applicationId 'com.topsai.dishwasher'; minSdk 26; targetSdk 36; versionCode 13; versionName '1.0.12'; testInstrumentationRunner 'android.test.InstrumentationTestRunner' }
 buildFeatures { buildConfig true }
 compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies { testImplementation 'junit:junit:4.13.2'; testImplementation 'org.json:json:20240303' }
